/// Base class for all exceptions in this library
abstract class MySQLException implements Exception {
  final String message;

  const MySQLException(this.message);

  String get _prefix;

  @override
  String toString() {
    return '$_prefix: $message';
  }
}

/// Class for errors generated by mysql server itself
///
/// Extends [MySQLException]. MySQL error code can be read from [errorCode]
class MySQLServerException extends MySQLException {
  /// MySQL server error code
  final int errorCode;

  const MySQLServerException(super.message, this.errorCode);

  @override
  String toString() {
    return '$_prefix [$errorCode]: $message';
  }

  @override
  String get _prefix => 'MySQLServerException';
}

/// Class for exceptions generated by this library
///
/// Extends [MySQLException]
class MySQLClientException extends MySQLException {
  const MySQLClientException(super.message);

  @override
  String get _prefix => 'MySQLClientException';
}

/// Class for mysql protocol specific exceptions
///
/// Extends [MySQLClientException]
class MySQLProtocolException extends MySQLClientException {
  const MySQLProtocolException(super.message);

  @override
  String get _prefix => 'MySQLProtocolException';
}

/// Reports a transaction failure together with a secondary rollback failure.
class MySQLTransactionException extends MySQLClientException {
  final Object cause;
  final StackTrace causeStackTrace;
  final Object rollbackCause;
  final StackTrace rollbackStackTrace;

  MySQLTransactionException({
    required this.cause,
    required this.causeStackTrace,
    required this.rollbackCause,
    required this.rollbackStackTrace,
  }) : super(
         'Transaction failed: $cause; rollback also failed: $rollbackCause',
       );
}
