/// Base class for all exceptions in this library
abstract class MysqlException implements Exception {
  final String message;

  const MysqlException(this.message);

  String get _prefix;

  @override
  String toString() {
    return '$_prefix: $message';
  }
}

/// Class for errors generated by mysql server itself
///
/// Extends [MysqlException]. MySQL error code can be read from [errorCode]
class MysqlServerException extends MysqlException {
  /// MySQL server error code
  final int errorCode;

  const MysqlServerException(super.message, this.errorCode);

  @override
  String toString() {
    return '$_prefix [$errorCode]: $message';
  }

  @override
  String get _prefix => 'MysqlServerException';
}

/// Class for exceptions generated by this library
///
/// Extends [MysqlException]
class MysqlClientException extends MysqlException {
  const MysqlClientException(super.message);

  @override
  String get _prefix => 'MysqlClientException';
}

/// Class for mysql protocol specific exceptions
///
/// Extends [MysqlClientException]
class MysqlProtocolException extends MysqlClientException {
  const MysqlProtocolException(super.message);

  @override
  String get _prefix => 'MysqlProtocolException';
}

/// Reports a transaction failure together with a secondary rollback failure.
class MysqlTransactionException extends MysqlClientException {
  final Object cause;
  final StackTrace causeStackTrace;
  final Object rollbackCause;
  final StackTrace rollbackStackTrace;

  MysqlTransactionException({
    required this.cause,
    required this.causeStackTrace,
    required this.rollbackCause,
    required this.rollbackStackTrace,
  }) : super(
         'Transaction failed: $cause; rollback also failed: $rollbackCause',
       );
}
